dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- pypy
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
script:
- python setup.py build
- cp -r build/lib*/elinks test/
- python test/test.py
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import elinks'

# vim:ts=2 sts=2 sw=2 et
